import 'package:flutter/material.dart';

class Constants {
  static const String appName = "Vivakti";
  static const String baseUrl = "https://your-api-domain.com/api/v1";

  // Colors
  static const Color primaryColor = Color(0xFFF88158);
  static const Color backgroundColor = Color(0xFFEFE1E1);
  static const Color textColor = Color(0xFF111810);

  // Categories
  static const List<String> categories = [
    "Plumber (repair/installation)",
    "Carpenter (repair/build)",
    "Electrician (repair/installation)",
    "AC technician (repair/installation)",
    "Washing Machine Repair (topload/frontload)",
    "Refrigerator Repair",
    "General Labour",
    "Househelp",
    "Cook",
    "Babysitter",
    "Gardener",
    "Logistics",
    "Packing worker",
    "Commercial Driver",
    "Lawyer & Legal Services",
    "Finance and Accounting",
    "Business and Management",
    "Technology",
    "Education and Professional Services",
    "Healthcare",
    "UI/UX Design",
    "Photo/Video Editing",
    "Graphic Designing",
    "Logo Making",
    "Content Writing",
    "Photography, Videography",
    "Interior Designer",
    "Interior Decorator",
    "Architect",
    "Product Design",
    "Music artists (Singing/instrument practice)",
    "Dance Artist",
    "Costume Designing and Tailoring",
    "Makeup artist",
    "Notary",
    "Lawyer - Sole and Junior",
    "Contract Specialist",
    "Property Consultant",
    "Corporate Compliance Consultant",
    "Management Consultant",
    "Finance & Accountant",
    "Financial Planner",
    "Accountant",
    "Audit",
    "Taxation",
    "GST filing",
    "Income tax filing",
    "Software Consultant",
    "AI consultant",
    "Web Dev Consultant",
    "Database Consultant",
    "HR Consultant",
    "Recruitment Consultant",
    "Data Analyst",
    "Marketing Specialist",
    "SEO Expert",
    "Content Strategist",
    "Digital Marketing",
    "App Developer",
    "Web Designer",
    "UI/UX Designer",
    "Video Editor",
    "Photographer",
    "Writer",
    "Translator",
    "Virtual Assistant",
    "Event Planner",
    "Fitness Trainer",
    "Nutritionist",
    "Therapist",
    "Counselor",
    "Pet Groomer",
    "House Cleaner",
    "Car Washer",
    "Plumber (Emergency)",
    "Electrician (Emergency)",
    "Carpenter (Emergency)",
    "AC Technician (Emergency)",
    "Washing Machine Repair (Emergency)",
    "Refrigerator Repair (Emergency)",
  ];
}
